sudo: required
services:
    - docker

before_install:
    - docker build -t  yakaman/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true yakaman/react-test npm test

after_success:
    - docker build -t yakaman/multi-client ./client
    - docker build -t yakaman/multi-nginx ./nginx
    - docker build -t yakaman/multi-server ./server
    - docker build -t yakaman/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push yakaman/multi-client
    - docker push yakaman/multi-nginx
    - docker push yakaman/multi-server
    - docker push yakaman/multi-worker